config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles
  resources :questions, only: [:new, :create]

  get 'basin_metrics/dashboard' => 'basin_metrics/dashboard#index'

  get 'basin_metrics/maps' => 'basin_metrics/maps#index'

  get 'basin_metrics/customers' => 'basin_metrics/customers#index'
  get 'basin_metrics/customers/new' => 'basin_metrics/customers#new'
  post 'basin_metrics/customers' => 'basin_metrics/customers#create'
  put 'basin_metrics/customers/:id' => 'basin_metrics/customers#update'
  delete 'basin_metrics/customers/:id' => 'basin_metrics/customers#destroy', as: 'basin_metrics_customer_delete'

  get 'basin_metrics/districts' => 'basin_metrics/districts#index'
  get 'basin_metrics/districts/new' => 'basin_metrics/districts#new'
  post 'basin_metrics/districts' => 'basin_metrics/districts#create'
  get 'basin_metrics/districts/:id' => 'basin_metrics/districts#show', as: 'basin_metrics_district_show'
  put 'basin_metrics/districts/:id' => 'basin_metrics/districts#update'
  delete 'basin_metrics/districts/:id' => 'basin_metrics/districts#destroy', as: 'basin_metrics_district_delete'

  get 'basin_metrics/wells' => 'basin_metrics/wells#index'
  get 'basin_metrics/wells/new' => 'basin_metrics/wells#new'
  post 'basin_metrics/wells' => 'basin_metrics/wells#create'
  get 'basin_metrics/wells/:id' => 'basin_metrics/wells#show', as: 'basin_metrics_well_show'
  put 'basin_metrics/wells/:id' => 'basin_metrics/wells#update'
  delete 'basin_metrics/wells/:id' => 'basin_metrics/wells#destroy', as: 'basin_metrics_well_delete'

  post 'basin_metrics/reservations/:id' => 'basin_metrics/reservations#create'

  get 'basin_metrics/parts' => 'basin_metrics/parts#index'
  get 'basin_metrics/parts/new' => 'basin_metrics/parts#new'
  post 'basin_metrics/parts' => 'basin_metrics/parts#create'
  put 'basin_metrics/parts/:id' => 'basin_metrics/parts#update'
  delete 'basin_metrics/parts/:id' => 'basin_metrics/parts#destroy', as: 'basin_metrics_part_delete'

  root 'welcome#index'

end

app/models/basin_metrics/company.rb
class BasinMetrics::Company < ActiveRecord::Base

  has_many :users
  has_many :customers, :class_name => 'BasinMetrics::Customer'
  has_many :districts, :class_name => 'BasinMetrics::District'
  has_many :wells, :class_name => 'BasinMetrics::Well', through: :districts
  has_many :parts, :class_name => 'BasinMetrics::Part', through: :districts

end

app/models/basin_metrics/customer.rb
class BasinMetrics::Customer < ActiveRecord::Base

  belongs_to :company, :class_name => 'BasinMetrics::Company'
  has_many :wells, :class_name => 'BasinMetrics::Well', dependent: :destroy
  has_many :districts, :class_name => 'BasinMetrics::District', through: :wells

  validates :name, presence: true

end

app/models/basin_metrics/district.rb
class BasinMetrics::District < ActiveRecord::Base

  belongs_to :company, :class_name => 'BasinMetrics::Company'

  has_many :wells, :class_name => 'BasinMetrics::Well', dependent: :destroy
  has_many :customers, :class_name => 'BasinMetrics::Customer', through: :wells
  has_many :parts, :class_name => 'BasinMetrics::Part', dependent: :destroy

  validates :name, presence: true

end

app/models/basin_metrics/part.rb
class BasinMetrics::Part < ActiveRecord::Base
  self.inheritance_column = nil #Disable STI for 'type' column

  belongs_to :district, :class_name => 'BasinMetrics::District'

  has_many :reservations, :class_name => 'BasinMetrics::Reservation'
  has_many :wells, :class_name => 'BasinMetrics::Well', through: :reservations

  validates :name, presence: true
  validates :type, presence: true
  validates :number, presence: true
  validates :order, presence: true, uniqueness: true
  validates :quantity, presence: true, numericality: :only_integer

  validates :district_id, presence: true

end

app/models/basin_metrics/reservation.rb
class BasinMetrics::Reservation < ActiveRecord::Base

  belongs_to :well, :class_name => 'BasinMetrics::Well'
  belongs_to :part, :class_name => 'BasinMetrics::Part'

end

app/controllers/basin_metrics/customers_controller.rb
class BasinMetrics::CustomersController < ApplicationController

  before_action :get_customers

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_customer][:name] = params[:basin_metrics_customer][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_customer].merge!(company_id: "#{current_user.company.id}")
    @customer = BasinMetrics::Customer.new(customer_params)

    if @customer.save
      get_customers
      flash.now[:success] = 'Customer created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    customer_params[:name] = clean_name_param(customer_params[:name])
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.update(customer_params)
      get_customers
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.destroy
      get_customers
      flash.now[:success] = 'Customer deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def customer_params
    if params[:basin_metrics_customer]
      params.require(:basin_metrics_customer).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_customers
    @customers = current_user.reload.company.customers
    @customers = @customers.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/dashboard_controller.rb
class BasinMetrics::DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @customers = current_user.company.customers
    @districts = current_user.company.districts
  end

end

app/controllers/basin_metrics/districts_controller.rb
class BasinMetrics::DistrictsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_districts

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_district][:name] = params[:basin_metrics_district][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_district].merge!(company_id: "#{current_user.company.id}")
    @district = BasinMetrics::District.new(district_params)

    if @district.save
      get_districts
      flash.now[:success] = 'District created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @district = BasinMetrics::District.find(district_params[:id])
    @district = @district.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    district_params[:name] = clean_name_param(district_params[:name])
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.update(district_params)
      get_districts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.destroy
      get_districts
      flash.now[:success] = 'District deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def district_params
    if params[:basin_metrics_district]
      params.require(:basin_metrics_district).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_districts
    @districts = current_user.reload.company.districts
    @districts = @districts.map(&:attributes).to_json.html_safe
  end
end

app/controllers/basin_metrics/maps_controller.rb
class BasinMetrics::MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

end

app/controllers/basin_metrics/parts_controller.rb
class BasinMetrics::PartsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_parts

  PARTS_LIST_TITLE = 'INVENTORY'

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    part_params[:name] = part_params[:name].strip.downcase.parameterize.underscore
    @part = BasinMetrics::Part.new(part_params)

    if @part.save
      get_parts
      flash.now[:success] = 'Part created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    part_params[:name] = clean_name_param(part_params[:name])
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.update(part_params)
      get_parts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.destroy
      get_parts
      flash.now[:success] = 'Part deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def part_params
    if params[:basin_metrics_part]
      params.require(:basin_metrics_part).permit(:name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    else
      params.permit(:id, :name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    end
  end

  def get_parts
    @parts = current_user.reload.company.parts
    @parts = @parts.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/reservations_controller.rb
class BasinMetrics::ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    binding.pry
    part_id = BasinMetrics::Part.where(type: params['inventory_value']).first.id
    @reservation = BasinMetrics::Reservation.new(well_id: params[:id], part_id: part_id, quantity: params['qty_value'].to_i)
    if @reservation.save
      get_wells
      flash.now[:success] = 'Inventory reserved'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    else
      flash.now[:error] = 'Inventory reservation failed'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    end
  end

  private

  def reservation_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/wells_controller.rb
class BasinMetrics::WellsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_wells
  before_action :set_est_schedule_attributes, only: [:update]

  DATETIME_FIELDS = %w(work_start work_duration)

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    well_params[:name] = well_params[:name].strip.downcase.parameterize.underscore
    @well = BasinMetrics::Well.new(well_params)

    if @well.save
      get_wells
      flash.now[:success] = 'Well created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @well = BasinMetrics::Well.find(well_params[:id])
    @well = @well.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    well_params[:name] = clean_name_param(well_params[:name]) if well_params[:name].present?
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.update(well_params)
      get_wells
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.destroy
      get_wells
      flash.now[:success] = 'Well deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def well_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

  def set_est_schedule_attributes
    return if well_params[:est_schedule_range].blank?

    est_sch_range = params[:est_schedule_range]

    if est_sch_range.present?
      params.merge!(parseEstDateRange(est_sch_range))
      params.delete('est_schedule_range')
    end
  end

  def parseEstDateRange(sch_range)
    ranges = sch_range.split(' to ')
    {est_start: ranges.first, est_end: ranges.last}
  end


end

app/helpers/parts_helper.rb
module PartsHelper

  def get_part_customer_name(part_id)
    # current_user.company.parts.where(id: part_id).first.district.customer.name.titleize
  end

  def get_part_district(part_id)
    current_user.reload.company.parts.where(id: part_id).first.district.name.titleize
  end

  def get_well(id)
    BasinMetrics::Well.where(id: id).first
  end

  def get_district_options
    district_ids = current_user.company.districts.map(&:id)
    district_numbers = current_user.company.districts.map(&:name)
    districts_build_options(district_ids, district_numbers)
  end

  def get_monthly_plugs_sold
    get_plug_quantities('date_sold')
  end

  def select_options_tag(name='',select_options={},options={})
    #set selected from value
    selected = ''
    unless options[:value].blank?
      selected = options[:value]
      options.delete(:value)
    end
    select_tag(name,options_for_select(select_options,selected),options)
  end

  private

  def get_plug_quantities(target_attribute)
    current_year = Time.zone.now.strftime('%Y').to_i
    well_x_label = "Month of #{current_year}"
    well_y_label = 'Quantity'
    quantity_by_month = []
    (1..12).each do |m|
      first_day = Date.civil(current_year, m, 1).to_datetime.utc
      last_day = Date.civil(current_year, m, -1).to_datetime.utc
      plugs = current_user.company.parts.where(name: 'plug', "#{target_attribute}": first_day..last_day)
      quantity = plugs.collect(&:quantity)
      quantity_by_month << quantity.sum
    end
    {array: quantity_by_month, x_label: well_x_label, y_label: well_y_label}
  end

  def districts_build_options(ids, name)
    options = [['district', '']]
    ids.each_with_index do |part_id, index|
      options << [name[index], part_id]
    end
    options
  end

end

app/views/basin_metrics/parts/_focus_index.haml
%canvas(id="partsChart" width="1500px" height="1500px")

:javascript
  var dyn_width = $('.focus_pane').width() + 'px'
  $('canvas').attr('height', dyn_width);

  var dyn_height = $('.focus_pane').height() + 'px'
  $('canvas').attr('height', dyn_height);
  var ctx = $("#partsChart");
  var myChart = new Chart(ctx, {
    data: {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'],
      datasets: [{
        type: 'line',
        label: 'Plugs Sold',
        data: #{get_monthly_plugs_sold[:array]},
        backgroundColor: "rgba(75, 192, 192, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        pointRadius: 3,
        pointHoverRadius: 5,
        borderWidth: 1
      }]
    },
    options: {
      responsive: true,
      responsiveAnimationDuration: 1000,
      maintainAspectRatio: false,
      scaleFontColor: "#fff",
      tooltips: {
        mode: 'index',
        intersect: false
      },
      scales: {
        xAxes: [{
          scaleLabel: {
            display: true,
            labelString: "#{get_monthly_plugs_sold[:x_label]}"
          },
          gridLines: {
            display: true,
          },
          ticks: {
            beginAtZero: true,
            fontColor: "#9faeaf"
          }
        }],
        yAxes: [{
            stacked: true,
            scaleLabel: {
            display: true,
            labelString: "#{get_monthly_plugs_sold[:y_label]}"
          },
          ticks: {
            beginAtZero: true,
            fontColor: "#9faeaf",
            suggestedMin: 0
          }
        }]
      }
    }
  });

app/views/basin_metrics/parts/_list_index.haml
.list_options
  .title= BasinMetrics::PartsController::PARTS_LIST_TITLE
  - if current_user.company.districts.exists?
    = link_to(material_icon.add_circle_outline, basin_metrics_parts_new_path, remote: true)

.list_content
  - if !current_user.company.districts.exists?
    .no_record
      Please add some Districts first
  - elsif current_user.company.parts.exists?
    %table.list_table
      - %W(name type number size quantity order_number revenue date_sold district_id).each do |heading|
        %th.part_heading= heading.titleize
      - parts.each_with_index do |part|
        %tr.record.part_record{'data-partid': part['id']}
          %td.record_attribute{'data-name':'name'}
            %div= part['name'].humanize
          %td.record_attribute{'data-name':'type'}
            %div= part['type']
          %td.record_attribute{'data-name':'number'}
            %div= part['number']
          %td.record_attribute.nullable{'data-name':'size'}
            %div= part['size'].blank? ? 'none' : part['size']
          %td.record_attribute{'data-name':'quantity'}
            %div= part['quantity']
          %td.record_attribute{'data-name':'order'}
            %div= part['order']
          %td.record_attribute{'data-name':'revenue'}
            %div= part['revenue']
          %td.record_attribute.nullable{'data-name':'date_sold'}
            %input.date_selector{value: part['date_sold'], placeholder: "#{part['date_sold'].blank? ? 'pending' : part['date_sold']}"}
          %td.record_attribute{'data-name':'district_id'}
            %div= get_part_district(part['id'])
          %td.remove_circle= link_to(material_icon.remove_circle_outline, basin_metrics_part_delete_path(part['id']), method: :delete, remote: true)
  - else
    .no_record
      No Parts Added yet - Go ahead and add some!

:javascript
  setNullableFieldColors();

  $(document).ready(function(){
    var date_selectors = $('.date_selector');
    flatpickr(".date_selector", {
      utc: true,
      enableTime: true,
      weekNumbers: true,
      altInput: true,
      altFormat: "F j, Y h:i K",

      onClose: function(selectedDates, dateStr, instance) {
        var $el = $(instance.element._flatpickr.altInput);
        var new_content = $el.val();
        sendUpdate($el, new_content);
      }
    });
    date_selectors.each(function(){$(this).remove()}); //Remove duplicate inputs
  });

app/views/basin_metrics/parts/_list_options_create_form.haml
.title= BasinMetrics::PartsController::PARTS_LIST_TITLE

= form_for BasinMetrics::Part.new, :method => :post, html: {class: 'create_line_form'}, remote: true do |f|
  = f.select(:name, [['part name', ''],['plug', 'plug'], ['pin_on_adapter', 'pin_on_adapter'], ['setting_sleeve', 'setting_sleeve']])
  = f.select(:type, [['part type', ''],['8k Trufrac', '8k_trufrak'], ['10k Trufrac', '10k_trufrac'], ['12k Fracshield', '12k_fracshield']])
  = f.text_field "number", placeholder: "part number"
  = f.select(:size, [['part size', ''],['none', 'NULL'], ['4.5 in', '4.5']])
  = f.text_field "order", placeholder: "order number"
  = f.text_field "quantity", placeholder: "quantity"
  = f.select(:district_id, options_for_select(get_district_options))
  = f.submit "Submit"
  = link_to "cancel", '/basin_metrics/parts', remote: true

app/views/basin_metrics/parts/index.js.erb
var focusPartial = "<%= j(render partial: 'basin_metrics/dashboard/focus_pane') %>";
var listPartial = "<%= j(render partial: 'basin_metrics/dashboard/list_pane') %>";
var indexFocusPartial = "<%= j(render partial: 'focus_index', locals: { parts: JSON.parse(@parts) }) %>";
var indexListPartial = "<%= j(render partial: 'list_index', locals: { parts: JSON.parse(@parts) }) %>";

// clear and build main pane
$('.main_pane').html(focusPartial).append(listPartial);
$('.list_pane').html(indexListPartial);
$('.focus_pane').html(indexFocusPartial);

triggerNotification("<%=j(flash.now[:success])%>", "<%=j(flash.now[:error])%>");