config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles
  resources :questions, only: [:new, :create]

  get 'basin_metrics/dashboard' => 'basin_metrics/dashboard#index'

  get 'basin_metrics/maps' => 'basin_metrics/maps#index'

  get 'basin_metrics/customers' => 'basin_metrics/customers#index'
  get 'basin_metrics/customers/new' => 'basin_metrics/customers#new'
  post 'basin_metrics/customers' => 'basin_metrics/customers#create'
  put 'basin_metrics/customers/:id' => 'basin_metrics/customers#update'
  delete 'basin_metrics/customers/:id' => 'basin_metrics/customers#destroy', as: 'basin_metrics_customer_delete'

  get 'basin_metrics/districts' => 'basin_metrics/districts#index'
  get 'basin_metrics/districts/new' => 'basin_metrics/districts#new'
  post 'basin_metrics/districts' => 'basin_metrics/districts#create'
  get 'basin_metrics/districts/:id' => 'basin_metrics/districts#show', as: 'basin_metrics_district_show'
  put 'basin_metrics/districts/:id' => 'basin_metrics/districts#update'
  delete 'basin_metrics/districts/:id' => 'basin_metrics/districts#destroy', as: 'basin_metrics_district_delete'

  get 'basin_metrics/wells' => 'basin_metrics/wells#index'
  get 'basin_metrics/wells/new' => 'basin_metrics/wells#new'
  post 'basin_metrics/wells' => 'basin_metrics/wells#create'
  get 'basin_metrics/wells/:id' => 'basin_metrics/wells#show', as: 'basin_metrics_well_show'
  put 'basin_metrics/wells/:id' => 'basin_metrics/wells#update'
  delete 'basin_metrics/wells/:id' => 'basin_metrics/wells#destroy', as: 'basin_metrics_well_delete'

  post 'basin_metrics/reservations/:id' => 'basin_metrics/reservations#create'

  get 'basin_metrics/parts' => 'basin_metrics/parts#index'
  get 'basin_metrics/parts/new' => 'basin_metrics/parts#new'
  post 'basin_metrics/parts' => 'basin_metrics/parts#create'
  put 'basin_metrics/parts/:id' => 'basin_metrics/parts#update'
  delete 'basin_metrics/parts/:id' => 'basin_metrics/parts#destroy', as: 'basin_metrics_part_delete'

  root 'welcome#index'

end

app/models/basin_metrics/company.rb
class BasinMetrics::Company < ActiveRecord::Base

  has_many :users
  has_many :customers, :class_name => 'BasinMetrics::Customer'
  has_many :districts, :class_name => 'BasinMetrics::District'
  has_many :wells, :class_name => 'BasinMetrics::Well', through: :districts
  has_many :parts, :class_name => 'BasinMetrics::Part', through: :districts

end

app/models/basin_metrics/customer.rb
class BasinMetrics::Customer < ActiveRecord::Base

  belongs_to :company, :class_name => 'BasinMetrics::Company'
  has_many :wells, :class_name => 'BasinMetrics::Well', dependent: :destroy
  has_many :districts, :class_name => 'BasinMetrics::District', through: :wells

  validates :name, presence: true

end

app/controllers/basin_metrics/customers_controller.rb
class BasinMetrics::CustomersController < ApplicationController

  before_action :get_customers

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_customer][:name] = params[:basin_metrics_customer][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_customer].merge!(company_id: "#{current_user.company.id}")
    @customer = BasinMetrics::Customer.new(customer_params)

    if @customer.save
      get_customers
      flash.now[:success] = 'Customer created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    customer_params[:name] = clean_name_param(customer_params[:name])
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.update(customer_params)
      get_customers
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.destroy
      get_customers
      flash.now[:success] = 'Customer deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def customer_params
    if params[:basin_metrics_customer]
      params.require(:basin_metrics_customer).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_customers
    @customers = current_user.reload.company.customers
    @customers = @customers.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/dashboard_controller.rb
class BasinMetrics::DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @customers = current_user.company.customers
    @districts = current_user.company.districts
  end

end

app/controllers/basin_metrics/districts_controller.rb
class BasinMetrics::DistrictsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_districts

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_district][:name] = params[:basin_metrics_district][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_district].merge!(company_id: "#{current_user.company.id}")
    @district = BasinMetrics::District.new(district_params)

    if @district.save
      get_districts
      flash.now[:success] = 'District created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @district = BasinMetrics::District.find(district_params[:id])
    @district = @district.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    district_params[:name] = clean_name_param(district_params[:name])
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.update(district_params)
      get_districts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.destroy
      get_districts
      flash.now[:success] = 'District deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def district_params
    if params[:basin_metrics_district]
      params.require(:basin_metrics_district).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_districts
    @districts = current_user.reload.company.districts
    @districts = @districts.map(&:attributes).to_json.html_safe
  end
end

app/controllers/basin_metrics/maps_controller.rb
class BasinMetrics::MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

end

app/controllers/basin_metrics/parts_controller.rb
class BasinMetrics::PartsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_parts

  PARTS_LIST_TITLE = 'INVENTORY'

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    part_params[:name] = part_params[:name].strip.downcase.parameterize.underscore
    @part = BasinMetrics::Part.new(part_params)

    if @part.save
      get_parts
      flash.now[:success] = 'Part created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    part_params[:name] = clean_name_param(part_params[:name])
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.update(part_params)
      get_parts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.destroy
      get_parts
      flash.now[:success] = 'Part deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def part_params
    if params[:basin_metrics_part]
      params.require(:basin_metrics_part).permit(:name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    else
      params.permit(:id, :name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    end
  end

  def get_parts
    @parts = current_user.reload.company.parts
    @parts = @parts.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/reservations_controller.rb
class BasinMetrics::ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    binding.pry
    part_id = BasinMetrics::Part.where(type: params['inventory_value']).first.id
    @reservation = BasinMetrics::Reservation.new(well_id: params[:id], part_id: part_id, quantity: params['qty_value'].to_i)
    if @reservation.save
      get_wells
      flash.now[:success] = 'Inventory reserved'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    else
      flash.now[:error] = 'Inventory reservation failed'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    end
  end

  private

  def reservation_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/wells_controller.rb
class BasinMetrics::WellsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_wells
  before_action :set_est_schedule_attributes, only: [:update]

  DATETIME_FIELDS = %w(work_start work_duration)

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    well_params[:name] = well_params[:name].strip.downcase.parameterize.underscore
    @well = BasinMetrics::Well.new(well_params)

    if @well.save
      get_wells
      flash.now[:success] = 'Well created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @well = BasinMetrics::Well.find(well_params[:id])
    @well = @well.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    well_params[:name] = clean_name_param(well_params[:name]) if well_params[:name].present?
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.update(well_params)
      get_wells
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.destroy
      get_wells
      flash.now[:success] = 'Well deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def well_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

  def set_est_schedule_attributes
    return if well_params[:est_schedule_range].blank?

    est_sch_range = params[:est_schedule_range]

    if est_sch_range.present?
      params.merge!(parseEstDateRange(est_sch_range))
      params.delete('est_schedule_range')
    end
  end

  def parseEstDateRange(sch_range)
    ranges = sch_range.split(' to ')
    {est_start: ranges.first, est_end: ranges.last}
  end


end

app/helpers/wells_helper.rb
module WellsHelper

  def format_date(time)
    DateTime.parse(time).strftime('%b %d, %Y')
  end

  def get_customers_options
    customer_ids = current_user.company.customers.order(:name).map(&:id)
    customer_names = current_user.company.customers.order(:name).map(&:name)

    build_options(customer_ids, customer_names)
  end

  def get_customer_well_counts
    well_x_label = 'Customer'
    well_y_label = 'Well Count'
    customers = BasinMetrics::Customer.all.order(:name)
    well_count_array = customers.collect do |c|
      current_user.company.wells.where(customer_id: c).size
    end
    {array: well_count_array, x_label: well_x_label, y_label: well_y_label}
  end

  def get_districts_options
    district_ids = current_user.company.districts.order(:name).map(&:id)
    district_names = current_user.company.districts.order(:name).map(&:name)

    build_options(district_ids, district_names)
  end

  def get_background_colors
    # customer_count = current_user.company.wells.order(:name).collect(&:name).size
    background_colors = []
    24.times {background_colors << 'rgba(75, 192, 192, 0.2)'}
    background_colors
    # [ 'rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)', 'rgba(255, 206, 86, 0.2)', 'rgba(75, 192, 192, 0.2)', 'rgba(153, 102, 255, 0.2)', 'rgba(255, 159, 64, 0.2)']
  end

  def get_border_colors
    # customer_count = current_user.company.wells.order(:name).collect(&:name).size
    border_colors = []
    24.times {border_colors << 'rgba(75, 192, 192, 1)'}
    border_colors
    # ['rgba(255,99,132,1)', 'rgba(54, 162, 235, 1)', 'rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(255, 159, 64, 1)']
  end

  def get_monthly_wells_completed
    get_completion_revenue_quantities('completed')
  end

  def get_reservation_options
    part_types = current_user.company.parts.order(:type).map(&:type).uniq
    part_types.zip(part_types)
  end

  def get_reserved_type(well_id)
    well_parts = BasinMetrics::Well.find(well_id).parts
    well_parts.blank? ? 'none' : well_parts.where(name: 'plug').first.type
  end

  def get_reserved_qty(well_id)
    reserved_qty = BasinMetrics::Well.find(well_id).reservations.map(&:quantity)
    reserved_qty.first.blank? ? 0 : reserved_qty.first
  end

  private

  def build_options(ids, names)
    options = []
    ids.each_with_index do |id, index|
      options << [names[index], id]
    end
    options
  end

  def get_completion_revenue_quantities(target_attribute)
    current_year = Time.zone.now.strftime('%Y').to_i
    last_year = Time.zone.now.last_year.strftime('%Y').to_i
    well_x_label = "#{last_year} to #{current_year}"
    well_y_label = 'Quantity'
    completions_by_month = []
    revenues_by_month = []
    [last_year,current_year].each do |y|
      (1..12).each do |m|
        first_day = Date.civil(y, m, 1).to_datetime.utc
        last_day = Date.civil(y, m, -1).to_datetime.utc
        completions = current_user.company.wells.where("#{target_attribute}": first_day..last_day)
        revenues = current_user.company.wells.where("#{target_attribute}": first_day..last_day, revenue: 0..Float::INFINITY).map(&:revenue)
        completions_by_month << completions.size
        revenues_by_month << revenues.sum
      end
    end
    revenues_by_month.map!{|r| r/1000}
    {completion_array: completions_by_month, revenue_array: revenues_by_month, x_label: well_x_label, y_label: well_y_label}
  end

end

app/views/basin_metrics/wells/_focus_index.haml
%canvas(id="wellsChart" width="1500px" height="1500px")

:javascript
  var dyn_width = $('.focus_pane').width() + 'px'
  $('canvas').attr('height', dyn_width);

  var dyn_height = $('.focus_pane').height() + 'px'
  $('canvas').attr('height', dyn_height);
  var ctx = $("#wellsChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: #{%W(jan'16 feb'16 mar'16 apr'16 may'16 jun'16 jul'16 aug'16 sep'16 oct'16 nov'16 dec'16 jan'17 feb'17 mar'17 apr'17 may'17 jun'17 jul'17 aug'17 sep'17 oct'17 nov'17 dec'17)},
      datasets: [{
        label: 'Wells Completed',
        type: 'bar',
        data: #{get_monthly_wells_completed[:completion_array]},
        backgroundColor: #{get_background_colors},
        borderColor: #{get_border_colors},
        borderWidth: 1
      },{
        label: 'Revenue (k)',
        type: 'line',
        data: #{get_monthly_wells_completed[:revenue_array]},
        fill: false,
        borderDash: [5, 4],
        backgroundColor: "rgba(75, 192, 192, 0.2)",
        borderColor: "rgba(75, 192, 192, 1)",
        pointRadius: 3,
        pointHoverRadius: 5,
        borderWidth: 1
      }]
    },
    options: {
      responsive: true,
      responsiveAnimationDuration: 1000,
      maintainAspectRatio: false,
      scaleFontColor: "#fff",
      tooltips: {
        mode: 'index',
        intersect: false
      },
      scales: {
        xAxes: [{
          scaleLabel: {
            display: true,
            labelString: "#{get_monthly_wells_completed[:x_label]}"
          },
          gridLines: {
            display: true,
          },
          ticks: {
            beginAtZero: true,
            fontColor: "#9faeaf"
          }
        }],
        yAxes: [{
            stacked: true,
            scaleLabel: {
            display: true,
            labelString: "#{get_monthly_wells_completed[:y_label]}"
          },
          ticks: {
            beginAtZero: true,
            fontColor: "#9faeaf",
            suggestedMin: 0
          }
        }]
      }
    }
  });

app/views/basin_metrics/wells/_form.haml
.list_options
  = form_for BasinMetrics::Well.new, :method => :post, html: {class: 'well_form'}, remote: true do |f|
    = f.text_field "name", placeholder: "well name"
    = f.text_field "number", placeholder: "well number"
    = f.label :pump_running, 'pump_running?'
    = f.check_box :pump_running
    = f.label :cemented, 'cemented?'
    = f.check_box :cemented
    = f.select :customer_id, options_for_select(get_customers)
    = f.select :district_id, options_for_select(get_districts)
    = f.submit "Submit"
    = link_to "cancel", '/basin_metrics/wells', remote: true

app/views/basin_metrics/wells/_list_index.haml
.list_options
  .title WELLS
  - if current_user.company.customers.exists? && current_user.company.districts.exists?
    = link_to(material_icon.add_circle_outline, basin_metrics_wells_new_path, remote: true)

.list_content
  - if !current_user.company.customers.exists?
    .no_record
      Please add some Customers first
  - elsif !current_user.company.districts.exists?
    .no_record
      Please add some Districts first
  - elsif current_user.company.wells.exists?
    %table.list_table
      - %W(#{''} name number pump_down_ring completed revenue customer district).each do |heading|
        %th.well_heading= heading.titleize
      - wells.each_with_index do |well|
        %tr.record.well_record{'data-wellid': well['id']}
          %td
            %div.examine_circle= link_to(material_icon.donut_large, basin_metrics_well_show_path(well['id']), method: :get, remote: true)
          %td.record_attribute{'data-name':'name'}
            %div= well['name'].humanize
          %td.record_attribute{'data-name':'number'}
            %div= well['number']
          %td.record_attribute.nullable{'data-name':'pump_down_ring'}
            = select_options_tag('pump_down_ring',[['3.70', '3.70'], ['3.79', '3.79']], value: well['pump_down_ring'], prompt: "none")
          %td.record_attribute.nullable{'data-name':'completed'}
            %input.list_date_selector{value: well['completed'].blank? ? '' : "#{format_date(well['completed'])}", placeholder: 'pending'}
          %td.record_attribute{'data-name':'revenue'}
            %div= well['revenue']
          %td.record_attribute{'data-name':'customer_id'}
            %div= get_customer(well['customer_id'].to_i).name.humanize
          %td.record_attribute{'data-name':'district_id'}
            %div= get_district(well['district_id'].to_i).name.humanize
          %td.remove_circle= link_to(material_icon.remove_circle_outline, basin_metrics_well_delete_path(well['id']), method: :delete, remote: true)
  - else
    .no_record
      No Wells Added yet - Go ahead and add some!


:javascript
  setNullableFieldColors();

  $(document).ready(function(){
    var list_date_selectors = $('.list_date_selector');
    flatpickr(".list_date_selector", {
      utc: true,
      weekNumbers: true,
      altInput: true,
      altFormat: "F j, Y",

      onClose: function(selectedDates, dateStr, instance) {
        var $el = $(instance.element._flatpickr.altInput);
        var new_content = $el.val();
        sendUpdate($el, new_content);
      }
    });
    list_date_selectors.each(function(){$(this).remove()}); //Remove duplicate inputs
  });

app/views/basin_metrics/wells/_list_options_create_form.haml
.title WELLS

= form_for BasinMetrics::Well.new, :method => :post, html: {class: 'create_line_form'}, remote: true do |f|
  = f.text_field "name", placeholder: "well name"
  = f.text_field "number", placeholder: "well number"
  = f.select(:pump_down_ring, [['pump down ring', 'none'],['none', 'none'],['3.70in', '3.70in'],['3.79in', '3.79in']])
  = f.label :cemented, 'cemented?'
  = f.check_box :cemented
  = f.select :customer_id, options_for_select(get_customers_options)
  = f.select :district_id, options_for_select(get_districts_options)
  = f.submit "Submit"
  = link_to "cancel", '/basin_metrics/wells', remote: true

app/views/basin_metrics/wells/_list_pane_create_form.haml
.list_options
  = form_for BasinMetrics::Well.new, :method => :post, html: {class: 'well_form'}, remote: true do |f|
    = f.text_field "name", placeholder: "well name"
    = f.text_field "number", placeholder: "well number"
    = f.label :pump_running, 'pump_running?'
    = f.check_box :pump_running
    = f.label :cemented, 'cemented?'
    = f.check_box :cemented
    = f.select :customer_id, options_for_select(get_customers)
    = f.select :district_id, options_for_select(get_districts)
    = f.submit "Submit"
    = link_to "cancel", '/basin_metrics/wells', remote: true

app/views/basin_metrics/wells/_record_show.haml
.progress_pane
  %div.close_circle= link_to(material_icon.cancel, basin_metrics_well_show_path(well['id']), method: :get, remote: true)
  .progress_content
    %div{id:"container"}
.record.record_description.well_record{'data-wellid': well['id']}
  %ul
    %li
      .title Well:
      .value #{well['name'].humanize} #{well['number']}
    %li
      .title % Complete:
      .record_attribute.value{'data-name':'percent_complete'}
        %div #{well['percent_complete']}
    %li
      .title Start/End Est:
      .record_attribute.nullable{'data-name':'est_schedule_range'}
        %input.date_selector_range{value: well['est_start'].blank? ? '' : "#{format_date(well['est_start'])} to #{format_date(well['est_end'])}", placeholder: 'pending'}
    %li
      .title Start Actual:
      .record_attribute.nullable{'data-name':'actual_start'}
        %input.date_selector{value: well['actual_start'].blank? ? '' : format_date(well['actual_start']), placeholder: 'pending'}
    %li.reservation
      .title Reserve Inventory:
      = select_options_tag('Inventory', get_reservation_options, value: get_reserved_type(well['id']), prompt: "none", class: 'number_selector')
      .title Qty:
      %input.number_selector{type:'number', min:0, value: get_reserved_qty(well['id'])}
      - if BasinMetrics::Well.find(well['id']).reservations.present?
        %span.locked= material_icon.lock
      - else
        %span.unlocked= material_icon.lock_open
    %li
      .title Directions:
      .value.comment= well['directions'].blank? ? 'none' : well['directions']
    %li
      .title Comments:
      .value.comment= well['comment'].blank? ? 'none' : well['comment']

:javascript

  var percent_complete = getWellPercentComplete();
  var stroke_width = 16;
  var bar = new ProgressBar.Circle(container, {
    color: '#CCDBDC', //Text color
    // This has to be the same size as the maximum width to
    // prevent clipping
    strokeWidth: stroke_width,
    trailWidth: 10,
    easing: 'easeInOut',
    duration: 1200,
    text: {
      autoStyleContainer: false
    },
    from: { color: '#9faeaf', width: 10 },
    to: { color: '#298889', width: stroke_width },
    // Set default step function for all animate calls
    step: function(state, circle) {
      circle.path.setAttribute('stroke', state.color);
      circle.path.setAttribute('stroke-width', state.width);

      var value = Math.round(circle.value() * 100);
      if (value === 0) {
        circle.setText('0' + '%');
      } else {
        circle.setText(value + '%');
      }

    }
  });
  bar.text.style.fontFamily = '"Raleway", Helvetica, sans-serif';
  bar.text.style.fontSize = '2rem';
  bar.animate(percent_complete);  // Number from 0.0 to 1.0

  $(document).ready(function(){
    var date_selectors = $('.date_selector');
    flatpickr(".date_selector", {
      utc: true,
      weekNumbers: true,
      altInput: true,
      altFormat: "M j, Y",

      onClose: function(selectedDates, dateStr, instance) {
        var $el = $(instance.element._flatpickr.altInput);
        var new_content = $el.val();
        sendUpdate($el, new_content);
      }
    });
    date_selectors.each(function(){$(this).remove()}); //Remove duplicate inputs

    var date_range_selectors = $('.date_selector_range');
    flatpickr(".date_selector_range", {
      utc: true,
      mode: 'range',
      weekNumbers: true,
      altInput: true,
      altFormat: "M j, Y",

      onClose: function(selectedDates, dateStr, instance) {
        var $el = $(instance.element._flatpickr.altInput);
        var new_content = $el.val();
        sendUpdate($el, new_content);
      }
    });
    date_range_selectors.each(function(){$(this).remove()}); //Remove duplicate inputs

    setLockTrigger(#{well['id']});
  });

  function getWellPercentComplete(){
    return (parseFloat("#{well['percent_complete']}"))/100;
  }