config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles
  resources :questions, only: [:new, :create]

  get 'basin_metrics/dashboard' => 'basin_metrics/dashboard#index'

  get 'basin_metrics/maps' => 'basin_metrics/maps#index'

  get 'basin_metrics/customers' => 'basin_metrics/customers#index'
  get 'basin_metrics/customers/new' => 'basin_metrics/customers#new'
  post 'basin_metrics/customers' => 'basin_metrics/customers#create'
  put 'basin_metrics/customers/:id' => 'basin_metrics/customers#update'
  delete 'basin_metrics/customers/:id' => 'basin_metrics/customers#destroy', as: 'basin_metrics_customer_delete'

  get 'basin_metrics/districts' => 'basin_metrics/districts#index'
  get 'basin_metrics/districts/new' => 'basin_metrics/districts#new'
  post 'basin_metrics/districts' => 'basin_metrics/districts#create'
  get 'basin_metrics/districts/:id' => 'basin_metrics/districts#show', as: 'basin_metrics_district_show'
  put 'basin_metrics/districts/:id' => 'basin_metrics/districts#update'
  delete 'basin_metrics/districts/:id' => 'basin_metrics/districts#destroy', as: 'basin_metrics_district_delete'

  get 'basin_metrics/wells' => 'basin_metrics/wells#index'
  get 'basin_metrics/wells/new' => 'basin_metrics/wells#new'
  post 'basin_metrics/wells' => 'basin_metrics/wells#create'
  get 'basin_metrics/wells/:id' => 'basin_metrics/wells#show', as: 'basin_metrics_well_show'
  put 'basin_metrics/wells/:id' => 'basin_metrics/wells#update'
  delete 'basin_metrics/wells/:id' => 'basin_metrics/wells#destroy', as: 'basin_metrics_well_delete'

  post 'basin_metrics/reservations/:id' => 'basin_metrics/reservations#create'

  get 'basin_metrics/parts' => 'basin_metrics/parts#index'
  get 'basin_metrics/parts/new' => 'basin_metrics/parts#new'
  post 'basin_metrics/parts' => 'basin_metrics/parts#create'
  put 'basin_metrics/parts/:id' => 'basin_metrics/parts#update'
  delete 'basin_metrics/parts/:id' => 'basin_metrics/parts#destroy', as: 'basin_metrics_part_delete'

  root 'welcome#index'

end

app/models/basin_metrics/company.rb
class BasinMetrics::Company < ActiveRecord::Base

  has_many :users
  has_many :customers, :class_name => 'BasinMetrics::Customer'
  has_many :districts, :class_name => 'BasinMetrics::District'
  has_many :wells, :class_name => 'BasinMetrics::Well', through: :districts
  has_many :parts, :class_name => 'BasinMetrics::Part', through: :districts

end

app/models/basin_metrics/customer.rb
class BasinMetrics::Customer < ActiveRecord::Base

  belongs_to :company, :class_name => 'BasinMetrics::Company'
  has_many :wells, :class_name => 'BasinMetrics::Well', dependent: :destroy
  has_many :districts, :class_name => 'BasinMetrics::District', through: :wells

  validates :name, presence: true

end

app/models/basin_metrics/district.rb
class BasinMetrics::District < ActiveRecord::Base

  belongs_to :company, :class_name => 'BasinMetrics::Company'

  has_many :wells, :class_name => 'BasinMetrics::Well', dependent: :destroy
  has_many :customers, :class_name => 'BasinMetrics::Customer', through: :wells
  has_many :parts, :class_name => 'BasinMetrics::Part', dependent: :destroy

  validates :name, presence: true

end

app/models/basin_metrics/part.rb
class BasinMetrics::Part < ActiveRecord::Base
  self.inheritance_column = nil #Disable STI for 'type' column

  belongs_to :district, :class_name => 'BasinMetrics::District'

  has_many :reservations, :class_name => 'BasinMetrics::Reservation'
  has_many :wells, :class_name => 'BasinMetrics::Well', through: :reservations

  validates :name, presence: true
  validates :type, presence: true
  validates :number, presence: true
  validates :order, presence: true, uniqueness: true
  validates :quantity, presence: true, numericality: :only_integer

  validates :district_id, presence: true

end

app/models/basin_metrics/reservation.rb
class BasinMetrics::Reservation < ActiveRecord::Base

  belongs_to :well, :class_name => 'BasinMetrics::Well'
  belongs_to :part, :class_name => 'BasinMetrics::Part'

end

app/controllers/basin_metrics/customers_controller.rb
class BasinMetrics::CustomersController < ApplicationController

  before_action :get_customers

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_customer][:name] = params[:basin_metrics_customer][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_customer].merge!(company_id: "#{current_user.company.id}")
    @customer = BasinMetrics::Customer.new(customer_params)

    if @customer.save
      get_customers
      flash.now[:success] = 'Customer created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    customer_params[:name] = clean_name_param(customer_params[:name])
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.update(customer_params)
      get_customers
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @customer = BasinMetrics::Customer.find(customer_params[:id])

    if @customer.destroy
      get_customers
      flash.now[:success] = 'Customer deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @customer.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def customer_params
    if params[:basin_metrics_customer]
      params.require(:basin_metrics_customer).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_customers
    @customers = current_user.reload.company.customers
    @customers = @customers.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/dashboard_controller.rb
class BasinMetrics::DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @customers = current_user.company.customers
    @districts = current_user.company.districts
  end

end

app/controllers/basin_metrics/districts_controller.rb
class BasinMetrics::DistrictsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_districts

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    params[:basin_metrics_district][:name] = params[:basin_metrics_district][:name].strip.downcase.parameterize.underscore
    params[:basin_metrics_district].merge!(company_id: "#{current_user.company.id}")
    @district = BasinMetrics::District.new(district_params)

    if @district.save
      get_districts
      flash.now[:success] = 'District created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @district = BasinMetrics::District.find(district_params[:id])
    @district = @district.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    district_params[:name] = clean_name_param(district_params[:name])
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.update(district_params)
      get_districts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @district = BasinMetrics::District.find(district_params[:id])

    if @district.destroy
      get_districts
      flash.now[:success] = 'District deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @district.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end


  private

  def district_params
    if params[:basin_metrics_district]
      params.require(:basin_metrics_district).permit(:name, :company_id)
    else
      params.permit(:id, :name, :company_id)
    end
  end

  def get_districts
    @districts = current_user.reload.company.districts
    @districts = @districts.map(&:attributes).to_json.html_safe
  end
end

app/controllers/basin_metrics/maps_controller.rb
class BasinMetrics::MapsController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

end

app/controllers/basin_metrics/parts_controller.rb
class BasinMetrics::PartsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_parts

  PARTS_LIST_TITLE = 'INVENTORY'

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    part_params[:name] = part_params[:name].strip.downcase.parameterize.underscore
    @part = BasinMetrics::Part.new(part_params)

    if @part.save
      get_parts
      flash.now[:success] = 'Part created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def update
    part_params[:name] = clean_name_param(part_params[:name])
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.update(part_params)
      get_parts
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @part = BasinMetrics::Part.find(part_params[:id])

    if @part.destroy
      get_parts
      flash.now[:success] = 'Part deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @part.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def part_params
    if params[:basin_metrics_part]
      params.require(:basin_metrics_part).permit(:name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    else
      params.permit(:id, :name, :type, :number, :size, :order, :quantity, :revenue, :date_sold, :district_id)
    end
  end

  def get_parts
    @parts = current_user.reload.company.parts
    @parts = @parts.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/reservations_controller.rb
class BasinMetrics::ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    binding.pry
    part_id = BasinMetrics::Part.where(type: params['inventory_value']).first.id
    @reservation = BasinMetrics::Reservation.new(well_id: params[:id], part_id: part_id, quantity: params['qty_value'].to_i)
    if @reservation.save
      get_wells
      flash.now[:success] = 'Inventory reserved'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    else
      flash.now[:error] = 'Inventory reservation failed'
      respond_to do |format|
        format.js { render '/wells/index', layout: false }
      end
    end
  end

  private

  def reservation_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

end

app/controllers/basin_metrics/wells_controller.rb
class BasinMetrics::WellsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_wells
  before_action :set_est_schedule_attributes, only: [:update]

  DATETIME_FIELDS = %w(work_start work_duration)

  def index
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def create
    well_params[:name] = well_params[:name].strip.downcase.parameterize.underscore
    @well = BasinMetrics::Well.new(well_params)

    if @well.save
      get_wells
      flash.now[:success] = 'Well created'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'new', layout: false }
      end
    end
  end

  def show
    @well = BasinMetrics::Well.find(well_params[:id])
    @well = @well.attributes.to_json.html_safe

    respond_to do |format|
      format.js { render 'show', layout: false }
    end
  end

  def update
    well_params[:name] = clean_name_param(well_params[:name]) if well_params[:name].present?
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.update(well_params)
      get_wells
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  def destroy
    @well = BasinMetrics::Well.find(well_params[:id])

    if @well.destroy
      get_wells
      flash.now[:success] = 'Well deleted'
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    else
      flash.now[:error] = @well.errors.full_messages.first
      respond_to do |format|
        format.js { render 'index', layout: false }
      end
    end
  end

  private

  def well_params
    if params[:basin_metrics_well]
      params.require(:basin_metrics_well).permit!
    else
      params.permit(:id, :name, :number, :est_schedule_range, :est_start, :actual_start, :est_end, :completed, :revenue, :pump_down_ring, :cemented, :customer_id, :district_id, :comments, :percent_complete)
    end
  end

  def get_wells
    @wells = current_user.reload.company.wells
    @wells = @wells.map(&:attributes).to_json.html_safe
  end

  def set_est_schedule_attributes
    return if well_params[:est_schedule_range].blank?

    est_sch_range = params[:est_schedule_range]

    if est_sch_range.present?
      params.merge!(parseEstDateRange(est_sch_range))
      params.delete('est_schedule_range')
    end
  end

  def parseEstDateRange(sch_range)
    ranges = sch_range.split(' to ')
    {est_start: ranges.first, est_end: ranges.last}
  end


end

app/helpers/district_helper.rb
module DistrictHelper

  COLOR_PRESENT = '#298889'
  COLOR_PRESENT_HOVER = '#33A8AA'
  COLOR_ABSENT = '#243038'
  COLOR_ABSENT_HOVER = '#2D3D47'

  def get_district_headings
    %W(#{''} name created_at updated_at)
  end

  def get_district_well_counts
    x_label = 'District'
    y_label = 'Well Count'
    districts = current_user.company.districts.order(:name)
    district_well_count = districts.collect{|d| d.wells.size}
    {array: district_well_count, x_label: x_label, y_label: y_label}
  end

  def get_district_customers(district_id)
    district = BasinMetrics::District.find(district_id)
    all_customers = BasinMetrics::Customer.all.map(&:name)
    district_customers = district.customers.order(:name).uniq.map(&:name)
    district_customers_colored = all_customers.map{|c| district_customers.include?(c) ? COLOR_PRESENT : COLOR_ABSENT}
    district_customers_data = district_customers_colored.collect{1}
    district_customers_hovered = district_customers_colored.collect{|c| (c == COLOR_PRESENT) ? COLOR_PRESENT_HOVER : COLOR_ABSENT_HOVER}
    {labels: all_customers, data: district_customers_data, colors: district_customers_colored, hovers: district_customers_hovered}
  end

end

app/views/basin_metrics/districts/_focus_index.haml
%canvas(id="districtsFocusChart" width="1500px" height="1500px")

:javascript
  var dyn_width = $('.focus_pane').width() + 'px'
  $('canvas').attr('height', dyn_width);

  var dyn_height = $('.focus_pane').height() + 'px'
  $('canvas').attr('height', dyn_height);

  var ctx = $("#districtsFocusChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: #{get_district_names},
      datasets: [{
        label: "#{get_district_well_counts[:y_label]} by #{get_district_well_counts[:x_label]}",
        data: #{get_district_well_counts[:array]},
        backgroundColor: #{get_background_colors},
        borderColor: #{get_border_colors},
        borderWidth: 1
      }]
    },
    options: {
      responsive: true,
      responsiveAnimationDuration: 1000,
      maintainAspectRatio: false,
      scaleFontColor: "#fff",
      scales: {
        xAxes: [{
          scaleLabel: {
            display: true,
            labelString: "#{get_district_well_counts[:x_label]}"
          },
          gridLines: {
            display: true,
          },
          ticks: {
            beginAtZero:true,
            fontColor: "#9faeaf"
          }
        }],
        yAxes: [{
            scaleLabel: {
            display: true,
            labelString: "#{get_district_well_counts[:y_label]}"
          },
          ticks: {
            beginAtZero:true,
            fontColor: "#9faeaf"
          }
        }]
      }
    }
  });

app/views/basin_metrics/districts/_list_index.haml
.list_options
  .title DISTRICTS
  = link_to(material_icon.add_circle_outline, basin_metrics_districts_new_path, remote: true)

.list_content
  - if current_user.company.districts.exists?
    %table.list_table
      - get_district_headings.each do |heading|
        %th.district_heading= heading.titleize
      - districts.each_with_index do |district|
        %tr.district_record{'data-districtid': district['id']}
          %td
            %div.examine_circle= link_to(material_icon.donut_large, basin_metrics_district_show_path(district['id']), method: :get, remote: true)
          %td.record_attribute{'data-name':'name'}= district['name'].humanize
          %td.record_attribute{'data-name':'created_at'}= district['created_at'].to_time.strftime("%b %e,%l:%M %p")
          %td.record_attribute{'data-name':'updated_at'}= district['updated_at'].to_time.strftime("%b %e,%l:%M %p")
          %td.remove_circle= link_to(material_icon.remove_circle_outline, basin_metrics_district_delete_path(district['id']), method: :delete, remote: true)
  - else
    .no_record
      No Districts Added yet - Go ahead and add some!

app/views/basin_metrics/districts/_list_options_create_form.haml
.title DISTRICTS

= form_for BasinMetrics::District.new, :method => :post, html: {class: 'create_line_form'}, remote: true do |f|
  = f.text_field "name", placeholder: "district name"
  = f.submit "Submit"
  = link_to "cancel", '/basin_metrics/districts', remote: true

app/views/basin_metrics/districts/_record_show.haml
.progress_pane
  %div.close_circle= link_to(material_icon.cancel, basin_metrics_district_show_path(district['id']), method: :get, remote: true)
  .progress_content
    %canvas(id="districtsRecordChart" width="150px" height="150px")
.record_description
  %ul
    %li
      .title Name:
      .value #{district['name'].humanize}

:javascript
  var ctx = $("#districtsRecordChart");
  var myPieChart = new Chart(ctx,{
    type: 'doughnut',
    data: {
      labels: #{get_district_customers(district['id'])[:labels]},
      datasets: [{
        data: #{get_district_customers(district['id'])[:data]},
        backgroundColor: #{get_district_customers(district['id'])[:colors]},
        hoverBackgroundColor: #{get_district_customers(district['id'])[:hovers]}
      }]
    },
    options: {
      responsive: true,
      responsiveAnimationDuration: 800,
      maintainAspectRatio: false,
      title: {
        display: true,
        text: "#{district['name'].humanize} Customers",
        fontFamily: 'Raleway'
      },
      legend: {
        display: false
      },
      cutoutPercentage: 70
    }
  });

app/views/basin_metrics/districts/index.js.erb
//Prepare structure
var focusPartial = "<%= j(render partial: 'basin_metrics/dashboard/focus_pane') %>";
var listPartial = "<%= j(render partial: 'basin_metrics/dashboard/list_pane') %>";
var recordPartial = "<%= j(render partial: 'basin_metrics/dashboard/record_pane') %>";

//Prepare pane contents
var indexFocusPartial = "<%= j(render partial: 'focus_index', locals: { districts: JSON.parse(@districts) }) %>";
var indexListPartial = "<%= j(render partial: 'list_index', locals: { districts: JSON.parse(@districts) }) %>";

// Add structure
$('.main_pane').html(recordPartial).append(focusPartial).append(listPartial);

//Fill pane contents
$('.list_pane').html(indexListPartial);
$('.focus_pane').html(indexFocusPartial);

triggerNotification("<%=j(flash.now[:success])%>", "<%=j(flash.now[:error])%>");

app/views/basin_metrics/districts/new.js.erb
var newView = "<%= j(render partial: 'list_options_create_form') %>";

$('.list_pane .list_options').empty().append(newView);

triggerNotification("<%=j(flash.now[:success])%>", "<%=j(flash.now[:error])%>");

app/views/basin_metrics/districts/show.js.erb
//Prepare pane contents
var record_pane = $('.record_pane');
var current_district = JSON.parse("<%= j( @district ) %>");
var district;

//Animate exit/entry
if (district === undefined){ //initial state
  openRecordPane(record_pane);
} else if ((current_district.id === district)){ //previously selected
  toggleRecordPane(record_pane);
} else if (record_pane.hasClass('showing')){
  replaceRecordPane(record_pane);
} else {
  openRecordPane(record_pane);
}
district = current_district.id;

function fillRecordPartial(){
  var showRecordPartial = "<%= j(render partial: 'record_show', locals: { district: JSON.parse(@district) }) %>";
  record_pane.html(showRecordPartial);
}

function closeRecordPane(el){
  el.animate({
    right: '-25%'
  },{
    duration: 200, easing: "easeInExpo"
  },{
    complete: function() {
      fillRecordPartial();
    }
  });
  el.removeClass('showing');
}

function replaceRecordPane(el){
  el.animate({
      right: '-25%'
    }, {
    duration: 200,
    easing: "easeInExpo",
    complete: function () {
      fillRecordPartial();
      el.removeClass('showing');
      openRecordPane(el);
    }
  });
}

function openRecordPane(el){
  fillRecordPartial();
  el.animate({right: 0},{duration: 300, easing: "easeOutExpo"});
  el.addClass('showing');
}

function toggleRecordPane(el){
  if (el.hasClass('showing')) {
    closeRecordPane(el);
  } else {
    openRecordPane(el);
  }
}